version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      docker-network:
        aliases:
          - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      docker-network:
        aliases:
          - kibana

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    container_name: logstash
    volumes:
      - ./logstash:/config-dir
    ports:
      - "8080:8080"
    command: logstash -f /config-dir/logstash.conf
    depends_on:
    - elasticsearch
    networks:
      docker-network:
        aliases:
          - logstash

  api:
    build: api/
    image: dockerdemo/api
    container_name: api
    hostname: dockerapi
    depends_on:
      - elasticsearch
      - kibana
      - logstash
    networks:
      docker-network:
        aliases:
          - dockerapi
    ports:
     - "80:80"
  
  client:
    build: client/
    image: dockerdemo/client
    depends_on:
      - api
    environment:
      SleepTime: 1000
      NumberOfRequests: 20
      ApiHost: dockerapi
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  elasticsearch-data:

configs:
  logstash:
    file: ./logstash.conf